"""Initial schema

Revision ID: fbc1af2190bd
Revises: 
Create Date: 2026-09-22 20:29:50.933101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc1af2190bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('data_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_sources_id'), 'dataset_sources', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('patient_code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_patient_code'), 'patients', ['patient_code'], unique=True)
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('rows_detected', sa.Integer(), nullable=True),
    sa.Column('rows_imported', sa.Integer(), nullable=True),
    sa.Column('rows_rejected', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_id'), 'import_jobs', ['id'], unique=False)
    op.create_table('pregnancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=True),
    sa.Column('pregnancy_code', sa.String(length=100), nullable=True),
    sa.Column('pregnancy_status', sa.String(length=50), nullable=True),
    sa.Column('conception_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_due_date', sa.DateTime(), nullable=True),
    sa.Column('pregnancy_start', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pregnancies_id'), 'pregnancies', ['id'], unique=False)
    op.create_index(op.f('ix_pregnancies_patient_id'), 'pregnancies', ['patient_id'], unique=False)
    op.create_table('vital_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('respiratory_rate', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('systolic_bp', sa.Float(), nullable=True),
    sa.Column('diastolic_bp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vital_signs_id'), 'vital_signs', ['id'], unique=False)
    op.create_index(op.f('ix_vital_signs_timestamp'), 'vital_signs', ['timestamp'], unique=False)
    op.create_table('clinical_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=True),
    sa.Column('pregnancy_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_events_id'), 'clinical_events', ['id'], unique=False)
    op.create_table('doctor_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=True),
    sa.Column('pregnancy_id', sa.Integer(), nullable=True),
    sa.Column('clinician_id', sa.String(length=100), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_reviews_id'), 'doctor_reviews', ['id'], unique=False)
    op.create_table('fetal_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregnancy_id', sa.Integer(), nullable=True),
    sa.Column('gestational_age_weeks', sa.Float(), nullable=True),
    sa.Column('trimester', sa.Integer(), nullable=True),
    sa.Column('crl', sa.Float(), nullable=True),
    sa.Column('nt', sa.Float(), nullable=True),
    sa.Column('nasal_bone', sa.String(length=50), nullable=True),
    sa.Column('efw', sa.Float(), nullable=True),
    sa.Column('efw_percentile', sa.Float(), nullable=True),
    sa.Column('growth_measurements', sa.Text(), nullable=True),
    sa.Column('assessment_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fetal_assessments_id'), 'fetal_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_fetal_assessments_pregnancy_id'), 'fetal_assessments', ['pregnancy_id'], unique=False)
    op.create_table('growth_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregnancy_id', sa.Integer(), nullable=True),
    sa.Column('predicted_efw_percentile', sa.Float(), nullable=True),
    sa.Column('actual_efw_percentile', sa.Float(), nullable=True),
    sa.Column('growth_variance', sa.Float(), nullable=True),
    sa.Column('evaluation_status', sa.String(length=100), nullable=True),
    sa.Column('contributing_patterns', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_analysis_id'), 'growth_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_growth_analysis_pregnancy_id'), 'growth_analysis', ['pregnancy_id'], unique=False)
    op.create_table('import_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('row_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_errors_id'), 'import_errors', ['id'], unique=False)
    op.create_table('maternal_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregnancy_id', sa.Integer(), nullable=True),
    sa.Column('maternal_age', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('map_value', sa.Float(), nullable=True),
    sa.Column('chronic_hypertension', sa.Boolean(), nullable=True),
    sa.Column('diabetes', sa.Boolean(), nullable=True),
    sa.Column('other_conditions', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maternal_profiles_id'), 'maternal_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_maternal_profiles_pregnancy_id'), 'maternal_profiles', ['pregnancy_id'], unique=False)
    op.create_table('newborns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregnancy_id', sa.Integer(), nullable=True),
    sa.Column('newborn_code', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('gestational_age_at_birth', sa.Float(), nullable=True),
    sa.Column('birth_weight', sa.Float(), nullable=True),
    sa.Column('birth_length', sa.Float(), nullable=True),
    sa.Column('birth_status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newborns_id'), 'newborns', ['id'], unique=False)
    op.create_index(op.f('ix_newborns_pregnancy_id'), 'newborns', ['pregnancy_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=True),
    sa.Column('pregnancy_id', sa.Integer(), nullable=True),
    sa.Column('clinician_id', sa.String(length=100), nullable=True),
    sa.Column('medication_name', sa.String(length=255), nullable=True),
    sa.Column('dosage', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=True),
    sa.Column('pregnancy_id', sa.Integer(), nullable=True),
    sa.Column('newborn_id', sa.Integer(), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['newborn_id'], ['newborns.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_table('doppler_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregnancy_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('gestational_age', sa.Float(), nullable=True),
    sa.Column('uterine_artery_pi', sa.Float(), nullable=True),
    sa.Column('uterine_artery_status', sa.String(length=50), nullable=True),
    sa.Column('umbilical_artery_status', sa.String(length=50), nullable=True),
    sa.Column('other_values', sa.Text(), nullable=True),
    sa.Column('test_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['fetal_assessments.id'], ),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doppler_results_id'), 'doppler_results', ['id'], unique=False)
    op.create_index(op.f('ix_doppler_results_pregnancy_id'), 'doppler_results', ['pregnancy_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregnancy_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('papp_a', sa.Float(), nullable=True),
    sa.Column('plgf', sa.Float(), nullable=True),
    sa.Column('free_beta_hcg', sa.Float(), nullable=True),
    sa.Column('test_date', sa.DateTime(), nullable=True),
    sa.Column('gestational_age', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['fetal_assessments.id'], ),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_results_id'), 'lab_results', ['id'], unique=False)
    op.create_index(op.f('ix_lab_results_pregnancy_id'), 'lab_results', ['pregnancy_id'], unique=False)
    op.create_table('nicu_admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newborn_id', sa.Integer(), nullable=True),
    sa.Column('admission_date', sa.DateTime(), nullable=True),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('admission_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['newborn_id'], ['newborns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nicu_admissions_id'), 'nicu_admissions', ['id'], unique=False)
    op.create_index(op.f('ix_nicu_admissions_newborn_id'), 'nicu_admissions', ['newborn_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=True),
    sa.Column('pregnancy_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('prediction_type', sa.String(length=100), nullable=True),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prediction_horizon', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('xgb_score', sa.Float(), nullable=True),
    sa.Column('cnn_lstm_score', sa.Float(), nullable=True),
    sa.Column('ae_score', sa.Float(), nullable=True),
    sa.Column('transformer_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['fetal_assessments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_pregnancy_id'), 'predictions', ['pregnancy_id'], unique=False)
    op.create_index(op.f('ix_predictions_timestamp'), 'predictions', ['timestamp'], unique=False)
    op.create_table('ultrasound_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregnancy_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('ultrasound_date', sa.DateTime(), nullable=True),
    sa.Column('gestational_age', sa.Float(), nullable=True),
    sa.Column('image_reference', sa.String(length=255), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('source_dataset', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['fetal_assessments.id'], ),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ultrasound_records_id'), 'ultrasound_records', ['id'], unique=False)
    op.create_index(op.f('ix_ultrasound_records_pregnancy_id'), 'ultrasound_records', ['pregnancy_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=True),
    sa.Column('newborn_id', sa.Integer(), nullable=True),
    sa.Column('nicu_admission_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('triggering_factors', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['newborn_id'], ['newborns.id'], ),
    sa.ForeignKeyConstraint(['nicu_admission_id'], ['nicu_admissions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('model_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=True),
    sa.Column('pregnancy_id', sa.Integer(), nullable=True),
    sa.Column('newborn_id', sa.Integer(), nullable=True),
    sa.Column('nicu_admission_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('input_reference', sa.Text(), nullable=True),
    sa.Column('output_type', sa.String(length=100), nullable=True),
    sa.Column('output_value', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('explanation_reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['newborn_id'], ['newborns.id'], ),
    sa.ForeignKeyConstraint(['nicu_admission_id'], ['nicu_admissions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_outputs_id'), 'model_outputs', ['id'], unique=False)
    op.create_table('nicu_vitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nicu_admission_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('respiratory_rate', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nicu_admission_id'], ['nicu_admissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nicu_vitals_id'), 'nicu_vitals', ['id'], unique=False)
    op.create_index(op.f('ix_nicu_vitals_nicu_admission_id'), 'nicu_vitals', ['nicu_admission_id'], unique=False)
    op.create_index(op.f('ix_nicu_vitals_timestamp'), 'nicu_vitals', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nicu_vitals_timestamp'), table_name='nicu_vitals')
    op.drop_index(op.f('ix_nicu_vitals_nicu_admission_id'), table_name='nicu_vitals')
    op.drop_index(op.f('ix_nicu_vitals_id'), table_name='nicu_vitals')
    op.drop_table('nicu_vitals')
    op.drop_index(op.f('ix_model_outputs_id'), table_name='model_outputs')
    op.drop_table('model_outputs')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_ultrasound_records_pregnancy_id'), table_name='ultrasound_records')
    op.drop_index(op.f('ix_ultrasound_records_id'), table_name='ultrasound_records')
    op.drop_table('ultrasound_records')
    op.drop_index(op.f('ix_predictions_timestamp'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_pregnancy_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_nicu_admissions_newborn_id'), table_name='nicu_admissions')
    op.drop_index(op.f('ix_nicu_admissions_id'), table_name='nicu_admissions')
    op.drop_table('nicu_admissions')
    op.drop_index(op.f('ix_lab_results_pregnancy_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_doppler_results_pregnancy_id'), table_name='doppler_results')
    op.drop_index(op.f('ix_doppler_results_id'), table_name='doppler_results')
    op.drop_table('doppler_results')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_newborns_pregnancy_id'), table_name='newborns')
    op.drop_index(op.f('ix_newborns_id'), table_name='newborns')
    op.drop_table('newborns')
    op.drop_index(op.f('ix_maternal_profiles_pregnancy_id'), table_name='maternal_profiles')
    op.drop_index(op.f('ix_maternal_profiles_id'), table_name='maternal_profiles')
    op.drop_table('maternal_profiles')
    op.drop_index(op.f('ix_import_errors_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index(op.f('ix_growth_analysis_pregnancy_id'), table_name='growth_analysis')
    op.drop_index(op.f('ix_growth_analysis_id'), table_name='growth_analysis')
    op.drop_table('growth_analysis')
    op.drop_index(op.f('ix_fetal_assessments_pregnancy_id'), table_name='fetal_assessments')
    op.drop_index(op.f('ix_fetal_assessments_id'), table_name='fetal_assessments')
    op.drop_table('fetal_assessments')
    op.drop_index(op.f('ix_doctor_reviews_id'), table_name='doctor_reviews')
    op.drop_table('doctor_reviews')
    op.drop_index(op.f('ix_clinical_events_id'), table_name='clinical_events')
    op.drop_table('clinical_events')
    op.drop_index(op.f('ix_vital_signs_timestamp'), table_name='vital_signs')
    op.drop_index(op.f('ix_vital_signs_id'), table_name='vital_signs')
    op.drop_table('vital_signs')
    op.drop_index(op.f('ix_pregnancies_patient_id'), table_name='pregnancies')
    op.drop_index(op.f('ix_pregnancies_id'), table_name='pregnancies')
    op.drop_table('pregnancies')
    op.drop_index(op.f('ix_import_jobs_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_patients_patient_code'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_dataset_sources_id'), table_name='dataset_sources')
    op.drop_table('dataset_sources')
    # ### end Alembic commands ###
