"""
=============================================================================
NeoNatal Watch AI — Dataset Loader
=============================================================================

Loads and standardizes data from:

1. PhysioNet CinC Challenge 2019 (primary — adult ICU sepsis, open access)
   URL: https://physionet.org/content/challenge-2019/1.0.0/
   Label: SepsisLabel (binary per-timestep)

2. PICS Database (supplemental — 10 preterm infants, open access)
   URL: https://physionet.org/content/picsdb/1.0.0/
   Label: Bradycardia annotations (derived)

3. Synthetic Data (always available — no access required)
   Generated by: ml/data/synthetic_generator.py

IMPORTANT:
  - CinC 2019 data is ADULT ICU data, not neonatal.
  - It is used as a reference dataset for prototype development.
  - All outputs from models trained on this data must clearly state:
    "Trained on adult ICU reference data (CinC 2019). Not neonatal data."
=============================================================================
"""

import os
import glob
import logging
from typing import Optional, Tuple, List

import numpy as np
import pandas as pd

logger = logging.getLogger("DataLoader")
logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")


# ─────────────────────────────────────────────────────────────────────────────
# COLUMN MAPPING — maps dataset-specific column names to our standard schema
# ─────────────────────────────────────────────────────────────────────────────

# Standard column names used throughout this project
STANDARD_VITALS = [
    "heart_rate",
    "spo2",
    "respiratory_rate",
    "temperature",
    "systolic_bp",
    "diastolic_bp",
]

# CinC 2019 PSV files use these column names
CINC2019_COLUMN_MAP = {
    "HR":    "heart_rate",
    "O2Sat": "spo2",
    "Resp":  "respiratory_rate",
    "Temp":  "temperature",
    "SBP":   "systolic_bp",
    "DBP":   "diastolic_bp",
    "MAP":   "mean_arterial_pressure",    # extra — keep if present
    "EtCO2": "etco2",                     # extra — keep if present
}

# Synthetic data already uses our standard column names


# ─────────────────────────────────────────────────────────────────────────────
# LOADER 1: CinC 2019 (Primary Dataset)
# ─────────────────────────────────────────────────────────────────────────────

def load_cinc2019(
    data_dir: str,
    max_patients: Optional[int] = None,
    verbose: bool = True,
) -> pd.DataFrame:
    """
    Load the PhysioNet CinC Challenge 2019 dataset from PSV files.

    ⚠️  This is ADULT ICU data, not neonatal data.
    Use it only for prototype development as a "reference ICU dataset".

    Parameters
    ----------
    data_dir : str
        Path to the directory containing .psv files (e.g., training_setA/).
    max_patients : int, optional
        Limit number of patients loaded (useful for quick testing).
    verbose : bool
        Whether to log progress.

    Returns
    -------
    pd.DataFrame
        Combined DataFrame with standardized column names:
        timestamp (reconstructed from ICULOS), patient_id, vital signs,
        SepsisLabel (renamed to deterioration_label).

    Columns output:
        patient_id, iculos, heart_rate, spo2, respiratory_rate,
        temperature, systolic_bp, diastolic_bp, deterioration_label, age, gender
    """
    psv_files = sorted(glob.glob(os.path.join(data_dir, "*.psv")))

    if not psv_files:
        logger.error(
            f"No .psv files found in {data_dir}. "
            f"Please download CinC 2019 data from: "
            f"https://physionet.org/content/challenge-2019/1.0.0/"
        )
        raise FileNotFoundError(
            f"CinC 2019 data not found in {data_dir}. "
            f"Download from https://physionet.org/content/challenge-2019/1.0.0/"
        )

    if max_patients is not None:
        psv_files = psv_files[:max_patients]

    if verbose:
        logger.info(f"Loading CinC 2019 data from {data_dir}")
        logger.info(f"Found {len(psv_files)} patient files")
        logger.info("⚠️  REMINDER: This is ADULT ICU data — not neonatal.")

    all_patients = []

    for fpath in psv_files:
        try:
            df = pd.read_csv(fpath, sep="|")
        except Exception as e:
            logger.warning(f"Could not load {fpath}: {e}")
            continue

        # Extract patient ID from filename (e.g., p000001.psv → p000001)
        patient_id = os.path.splitext(os.path.basename(fpath))[0]
        df["patient_id"] = patient_id

        # Rename columns to our standard schema
        df = df.rename(columns=CINC2019_COLUMN_MAP)

        # Rename the label column
        if "SepsisLabel" in df.columns:
            df = df.rename(columns={"SepsisLabel": "deterioration_label"})
        else:
            df["deterioration_label"] = np.nan

        # Add metadata columns
        df["data_source"] = "CINC2019_ADULT_ICU"
        df["data_warning"] = (
            "ADULT_ICU_REFERENCE_DATA_NOT_NEONATAL_NOT_FOR_CLINICAL_USE"
        )

        all_patients.append(df)

    if not all_patients:
        raise ValueError("No patient data could be loaded.")

    combined = pd.concat(all_patients, ignore_index=True)

    # ICULOS (ICU Length of Stay) is in hours — use it as a time proxy
    if "ICULOS" in combined.columns:
        combined = combined.rename(columns={"ICULOS": "iculos_hours"})

    if verbose:
        logger.info(f"Loaded {combined['patient_id'].nunique()} patients")
        logger.info(f"Total rows: {len(combined):,}")
        if "deterioration_label" in combined.columns:
            n_events = combined["deterioration_label"].sum()
            logger.info(
                f"Sepsis events: {n_events:.0f} "
                f"({n_events / len(combined) * 100:.1f}%)"
            )

    return combined


# ─────────────────────────────────────────────────────────────────────────────
# LOADER 2: PICS Database (Neonatal Waveforms)
# ─────────────────────────────────────────────────────────────────────────────

def load_pics_database(
    data_dir: str,
    derive_hr: bool = True,
    derive_rr: bool = True,
    verbose: bool = True,
) -> pd.DataFrame:
    """
    Load the Preterm Infant Cardio-Respiratory Signals (PICS) database.

    ✅ This is AUTHENTIC NEONATAL data (10 preterm infants).

    Requires the `wfdb` library: pip install wfdb

    The PICS database contains:
    - ECG signals (500 or 250 Hz)
    - Respiration signals (50 Hz)
    - Bradycardia annotations (atr files)

    This function:
    - Reads ECG and respiration WFDB records
    - Derives a coarse Heart Rate from RR intervals (qrsc annotations)
    - Derives a coarse Respiratory Rate from respiration annotations
    - Aligns with bradycardia annotations to create a label

    Parameters
    ----------
    data_dir : str
        Path to directory containing PICS WFDB files (.hea, .dat, .qrsc, .atr).
    derive_hr : bool
        Whether to derive HR from R-peak annotations.
    derive_rr : bool
        Whether to derive RR from respiration peak annotations.
    verbose : bool
        Whether to log progress.

    Returns
    -------
    pd.DataFrame
        DataFrame with columns:
        patient_id, window_index, heart_rate (derived), respiratory_rate (derived),
        bradycardia_label

    Note
    ----
    SpO2, Temperature, and Blood Pressure are NOT available in this dataset.
    Those columns will be NaN.
    """
    try:
        import wfdb
    except ImportError:
        raise ImportError(
            "The `wfdb` library is required to load PICS data. "
            "Install with: pip install wfdb"
        )

    if not os.path.isdir(data_dir):
        logger.error(
            f"PICS data directory not found: {data_dir}\n"
            f"Download from: https://physionet.org/content/picsdb/1.0.0/"
        )
        raise FileNotFoundError(
            f"PICS data directory not found: {data_dir}"
        )

    if verbose:
        logger.info(f"Loading PICS neonatal waveform data from {data_dir}")
        logger.info("✅ This is authentic neonatal data (10 preterm infants).")

    all_infants = []

    for infant_num in range(1, 11):
        ecg_record_name = f"infant{infant_num}_ecg"
        resp_record_name = f"infant{infant_num}_resp"
        ecg_path = os.path.join(data_dir, ecg_record_name)
        resp_path = os.path.join(data_dir, resp_record_name)

        if not os.path.exists(ecg_path + ".hea"):
            if verbose:
                logger.warning(f"Infant {infant_num} ECG record not found, skipping.")
            continue

        try:
            # Load ECG header and annotations
            ecg_header = wfdb.rdheader(ecg_path)
            fs_ecg = ecg_header.fs

            # Load bradycardia annotations (atr)
            try:
                brady_ann = wfdb.rdann(ecg_path, "atr")
                brady_samples = set(brady_ann.sample)
            except Exception:
                brady_samples = set()
                if verbose:
                    logger.warning(f"Infant {infant_num}: no bradycardia annotations.")

            # Load R-peak annotations (qrsc) to derive HR
            hr_estimates = []
            if derive_hr:
                try:
                    qrsc_ann = wfdb.rdann(ecg_path, "qrsc")
                    rpeaks = qrsc_ann.sample
                    # Compute instantaneous HR from RR intervals
                    rr_intervals = np.diff(rpeaks) / fs_ecg  # in seconds
                    inst_hr = 60.0 / rr_intervals  # bpm
                    # Clip to physiological range
                    inst_hr = np.clip(inst_hr, 60, 220)
                    hr_estimates = inst_hr.tolist()
                except Exception as e:
                    if verbose:
                        logger.warning(f"Infant {infant_num}: HR derivation failed: {e}")

            # Load respiration peak annotations to derive RR
            rr_estimates = []
            if derive_rr and os.path.exists(resp_path + ".hea"):
                try:
                    resp_ann = wfdb.rdann(resp_path, "resp")
                    resp_peaks = resp_ann.sample
                    resp_header = wfdb.rdheader(resp_path)
                    fs_resp = resp_header.fs
                    resp_intervals = np.diff(resp_peaks) / fs_resp  # seconds
                    inst_rr = 60.0 / resp_intervals  # breaths/min
                    inst_rr = np.clip(inst_rr, 10, 80)
                    rr_estimates = inst_rr.tolist()
                except Exception as e:
                    if verbose:
                        logger.warning(f"Infant {infant_num}: RR derivation failed: {e}")

            # Build a DataFrame for this infant
            # We use HR beats as the time reference
            n_beats = len(hr_estimates)
            if n_beats == 0:
                continue

            infant_df = pd.DataFrame()
            infant_df["patient_id"] = [f"PICS-{infant_num:02d}"] * n_beats
            infant_df["beat_index"] = range(n_beats)
            infant_df["heart_rate"] = hr_estimates

            # Align RR to HR length (they may differ)
            if rr_estimates:
                n_resp = len(rr_estimates)
                if n_resp >= n_beats:
                    infant_df["respiratory_rate"] = rr_estimates[:n_beats]
                else:
                    padded_rr = rr_estimates + [np.nan] * (n_beats - n_resp)
                    infant_df["respiratory_rate"] = padded_rr
            else:
                infant_df["respiratory_rate"] = np.nan

            # These signals are not in PICS
            infant_df["spo2"] = np.nan
            infant_df["temperature"] = np.nan
            infant_df["systolic_bp"] = np.nan
            infant_df["diastolic_bp"] = np.nan

            # Create label based on proximity to bradycardia annotations
            # A beat is labeled 1 if its sample index is near a bradycardia onset
            # (within 50 samples ≈ 0.1 s at 500 Hz — crude alignment)
            infant_df["deterioration_label"] = 0
            if brady_samples and derive_hr:
                try:
                    for brady_sample in brady_samples:
                        # Find beats within ±1 second of bradycardia onset
                        window_samples = fs_ecg  # 1 second
                        nearby_peaks = [
                            i for i, pk in enumerate(qrsc_ann.sample)
                            if abs(pk - brady_sample) < window_samples
                        ]
                        for idx in nearby_peaks:
                            if idx < n_beats:
                                infant_df.loc[idx, "deterioration_label"] = 1
                except Exception:
                    pass

            infant_df["data_source"] = "PICS_NEONATAL"
            infant_df["data_warning"] = "AUTHENTIC_NEONATAL_WAVEFORM_NOT_FOR_CLINICAL_USE"
            infant_df["clinical_event"] = infant_df["deterioration_label"].apply(
                lambda x: "bradycardia" if x == 1 else "none"
            )

            all_infants.append(infant_df)

            if verbose:
                n_events = infant_df["deterioration_label"].sum()
                logger.info(
                    f"  Infant {infant_num:02d}: "
                    f"{n_beats} beats, "
                    f"{n_events} bradycardia-labeled beats "
                    f"({n_events / n_beats * 100:.1f}%)"
                )

        except Exception as e:
            logger.error(f"Error loading infant {infant_num}: {e}")
            continue

    if not all_infants:
        raise ValueError(
            "No PICS data could be loaded. "
            "Check that WFDB files are present in the data directory."
        )

    combined = pd.concat(all_infants, ignore_index=True)

    if verbose:
        logger.info(f"PICS: loaded {combined['patient_id'].nunique()} infants")
        logger.info(f"PICS: total beats: {len(combined):,}")

    return combined


# ─────────────────────────────────────────────────────────────────────────────
# LOADER 3: Synthetic Data
# ─────────────────────────────────────────────────────────────────────────────

def load_synthetic_data(
    data_dir: str,
    verbose: bool = True,
) -> pd.DataFrame:
    """
    Load pre-generated synthetic NICU vital sign data.

    ⚠️  SYNTHETIC DATA — NOT FOR CLINICAL USE ⚠️

    Parameters
    ----------
    data_dir : str
        Directory containing synthetic_nicu_vitals.csv.
    verbose : bool
        Whether to log progress.

    Returns
    -------
    pd.DataFrame
        Synthetic vital sign data with all standard columns.
    """
    csv_path = os.path.join(data_dir, "synthetic_nicu_vitals.csv")

    if not os.path.exists(csv_path):
        logger.warning(
            f"Synthetic data not found at {csv_path}. "
            f"Run ml/data/synthetic_generator.py first."
        )
        raise FileNotFoundError(
            f"Synthetic data not found: {csv_path}. "
            f"Generate it with: python ml/data/synthetic_generator.py"
        )

    df = pd.read_csv(csv_path, parse_dates=["timestamp"])

    if verbose:
        logger.info(f"⚠️  Loaded SYNTHETIC data: {csv_path}")
        logger.info(f"    Patients: {df['patient_id'].nunique()}")
        logger.info(f"    Records:  {len(df):,}")
        logger.info("    This is NOT real patient data.")

    return df


# ─────────────────────────────────────────────────────────────────────────────
# UNIFIED LOADER
# ─────────────────────────────────────────────────────────────────────────────

def load_dataset(
    source: str,
    data_dir: str,
    max_patients: Optional[int] = None,
    verbose: bool = True,
) -> pd.DataFrame:
    """
    Unified dataset loader.

    Parameters
    ----------
    source : str
        One of: 'cinc2019', 'pics', 'synthetic'
    data_dir : str
        Path to the data directory for the selected source.
    max_patients : int, optional
        Limit (only for cinc2019).
    verbose : bool
        Log progress.

    Returns
    -------
    pd.DataFrame
        Standardized DataFrame for the selected source.
    """
    source = source.lower().strip()

    if source == "cinc2019":
        return load_cinc2019(data_dir, max_patients=max_patients, verbose=verbose)
    elif source == "pics":
        return load_pics_database(data_dir, verbose=verbose)
    elif source == "synthetic":
        return load_synthetic_data(data_dir, verbose=verbose)
    else:
        raise ValueError(
            f"Unknown source '{source}'. "
            f"Choose from: 'cinc2019', 'pics', 'synthetic'"
        )


# ─────────────────────────────────────────────────────────────────────────────
# DATASET AVAILABILITY CHECK
# ─────────────────────────────────────────────────────────────────────────────

def check_data_availability(base_data_dir: str) -> dict:
    """
    Check which datasets are available in the data directory.

    Parameters
    ----------
    base_data_dir : str
        Root data directory (e.g., data/).

    Returns
    -------
    dict
        Availability status for each dataset.
    """
    status = {
        "cinc2019": {
            "available": False,
            "path": os.path.join(base_data_dir, "raw", "challenge2019"),
            "note": "Download from: https://physionet.org/content/challenge-2019/1.0.0/",
        },
        "pics": {
            "available": False,
            "path": os.path.join(base_data_dir, "raw", "picsdb"),
            "note": "Download from: https://physionet.org/content/picsdb/1.0.0/",
        },
        "synthetic": {
            "available": False,
            "path": os.path.join(base_data_dir, "synthetic"),
            "note": "Generate with: python ml/data/synthetic_generator.py",
        },
    }

    # Check CinC 2019
    cinc_dir = status["cinc2019"]["path"]
    if os.path.isdir(cinc_dir):
        psv_files = glob.glob(os.path.join(cinc_dir, "*.psv"))
        if psv_files:
            status["cinc2019"]["available"] = True
            status["cinc2019"]["n_files"] = len(psv_files)

    # Check PICS
    pics_dir = status["pics"]["path"]
    if os.path.isdir(pics_dir):
        hea_files = glob.glob(os.path.join(pics_dir, "*.hea"))
        if hea_files:
            status["pics"]["available"] = True
            status["pics"]["n_files"] = len(hea_files)

    # Check synthetic
    syn_dir = status["synthetic"]["path"]
    syn_csv = os.path.join(syn_dir, "synthetic_nicu_vitals.csv")
    if os.path.exists(syn_csv):
        status["synthetic"]["available"] = True

    # Print report
    print("\n" + "=" * 55)
    print("NeoNatal Watch AI -- Dataset Availability Check")
    print("=" * 55)
    for name, info in status.items():
        avail = "[AVAILABLE]" if info["available"] else "[NOT FOUND]"
        print(f"\n[{name.upper()}]  {avail}")
        print(f"  Path: {info['path']}")
        if not info["available"]:
            print(f"  How to get: {info['note']}")
        else:
            if "n_files" in info:
                print(f"  Files found: {info['n_files']}")
    print("=" * 55 + "\n")

    return status


# ─────────────────────────────────────────────────────────────────────────────
# ENTRY POINT
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    """
    Run this script to check which datasets are available.

    Usage:
        python data_loader.py
    """
    # Construct path to the project data/ directory
    project_root = os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    )
    data_root = os.path.join(project_root, "data")

    status = check_data_availability(data_root)

    # Try loading synthetic data if available
    if status["synthetic"]["available"]:
        df = load_synthetic_data(status["synthetic"]["path"])
        print("Synthetic data preview:")
        print(df.head(3).to_string())
    else:
        print("No data available yet. Please follow the setup instructions.")
        print("Quick start: run `python ml/data/synthetic_generator.py` first.")
